apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app-deployment
spec:
  replicas: 2 # Define el número de instancias (Pods) que se desean ejecutar
  selector:
    matchLabels:
      app: inventario-app
  template:
    metadata:
      labels:
        app: inventario-app
    spec:
      containers:
        - name: inventario-container
          image: inventario-app:latest
          ports:
            - containerPort: 8080